sudo: required

services:
    - docker

before_install:
    - docker build -t kotharinilay/react-docker-test -f Dockerfile.dev .

script:
    - docker run -e CI=true kotharinilay/react-docker-test npm test -- --coverage